src/courses/tests.py
src/frontend/templates/index.html
src/settings/settings.py
src/static/auth.js

Use camelcase renderer

---

Readme.md

Created readme file

---

.github/workflows/config.yml
requirements.txt
src/auth_ex/apps.py
src/auth_ex/migrations/0001_initial.py
src/auth_ex/models.py
src/auth_ex/tests.py
src/aws/apps.py
src/aws/management/commands/bootstrap.py
src/aws/storages.py
src/courses/admin.py
src/courses/apps.py
src/courses/models.py
src/courses/permissions.py
src/courses/serializers.py
src/courses/signals.py
src/courses/tasks.py
src/courses/tests/test_api_access.py
src/courses/urls.py
src/courses/views.py
src/frontend/apps.py
src/frontend/urls.py
src/pyproject.toml
src/settings/__init__.py
src/settings/asgi.py
src/settings/celery.py
src/settings/settings.py
src/settings/urls.py
src/settings/wsgi.py

- Add isort requirement
- Isort config
- Initial isort usage
- Isort integrated with Github workflows
- Add build image step for unit tests for output clarity
- Add black requirement and config
- Initial black run
- Black integration with github workflow
Closes #47

issue 47 set up linter

---

src/courses/admin.py
src/courses/serializers.py
src/courses/tests/test_api.py
src/courses/views.py
src/frontend/templates/courses.html
src/static/css/courses.css
src/static/css/main.css
src/static/js/courses.js

- Send ID for course details
- Proper create endpoint for course signup
- Course signup action
- Proper error message for signing up for the same course
- Signup toast message
Closes #28

issue 28 signup for course interface

---

docker-compose.yml
src/courses/permissions.py
src/courses/serializers.py
src/courses/tests/test_api.py
src/courses/tests/test_serializers.py
src/courses/views.py

- Added endpoint for reordering with permissions checking
- Tests refactoring
- Tests for reordering sections
- Reordering logic implemented
- Tests for logic in serializer
- Code reformatting
Closes #55

issue 55 reorder course sections

---

docker-compose.yml
src/courses/permissions.py
src/courses/serializers.py
src/courses/tests/test_api.py
src/courses/tests/test_serializers.py
src/courses/views.py

Release 01.02.2021

---

.github/workflows/config.yml
src/courses/models.py
src/courses/querysets.py
src/courses/tests/test_api.py
src/courses/views.py
src/frontend/templates/courses.html
src/static/js/courses.js

Issue 57 list assigned courses

---

src/static/css/courses.css

added css property cursor pointer to all courses and own courses

added cursor pointer to courses list

---

src/courses/serializers.py
src/courses/tests/test_api.py
src/courses/views.py
src/frontend/templates/base.html
src/frontend/templates/course_details.html
src/frontend/templates/courses.html
src/frontend/urls.py
src/lessons/serializers.py
src/lessons/views.py
src/static/css/course_details.css
src/static/css/main.css
src/static/js/course_details.js
src/static/js/courses.js
src/static/js/error_handler.js

- Proper navigation.
- Redirect to course details
- Proper padding on main courses page
- Mock up data for sidebar rendering.
- Listing lessons and sections
- Endpoint for listing course details
- Present courses data on course details
- Separate lessons with border
- Display lesson contents
- Render lesson details depending on lesson type.
- Marking lessons as complete

issue 60 listing lessons

---

.env.example
src/courses/querysets.py
src/courses/tests/test_api.py
src/courses/views.py
src/lessons/models.py
src/lessons/tests/test_api.py
src/lessons/tests/test_models.py
src/lessons/views.py
src/settings/settings.py

- Database logging
- Limit the number of fields retrieved on courses views
- Annotate lesson completeness
- Use annotation in prefetch to limit the number of queries
- Fix errors from wrong query manager
- Fill tests for optimization
- Code reformatted
Closes #78

issue 78 optimize queries

---

src/auth_ex/tests.py

User access tests

---

src/settings/celery.py

Closes #73
Reference for the solution can be found here: https://www.mattlayman.com/blog/2017/django-celery-rollbar/

Celery setup for Handling Rollbar

---

.github/workflows/config.yml
.gitignore
requirements.txt
src/courses/querysets.py
src/lessons/models.py
src/lessons/serializers.py
src/mypy.ini

- Added mypy to requirements
- Upgraded dependencies
- Changed mypy cache ignore
- Changes to comply with mypy
- mypy configuration
- mypy configuration
- Added mypy to git config

issue 81 mypy

---

Readme.md
src/common/exceptions.py
src/lessons/models.py
src/lessons/tests/test_api.py
src/lessons/tests/test_models.py
src/lessons/views.py

- Implement new exception handling process
- Fix typos and language errors
- Update docs with error handling
Closes #89

issue 89 error handling

---

src/static/js/auth.js

Redirect from main page if user is logged in

---

src/aws/tests.py
src/aws/views.py
src/settings/urls.py

Endpoint for health checks

---

buildspec.yml

- Attempted to fix aws builds
- Delete unnecessary build step

aws build fails

---

buildspec.yml

This reverts commit 832bb77872d0b57b08130641195736e26955a447.

Revert "Delete unnecessary build step"

---

buildspec.yml

- Revert "Delete unnecessary build step"
- Fixes of docker login failed

add docker login

---

src/aws/secrets_retriever.py
src/settings/settings.py

- Proper logging
- Delete unused logging statements

delete unused logging statements

---

src/aws/storages.py
src/settings/settings.py

- Set S3 region to eu-west-1
- Use region name in storage client

fix aws region names

---

src/frontend/templates/course_details.html
src/static/js/course_details.js

- Clear answer labels
- Allow to move to previous question
Closes #109

issue 109 frontend bugs

---

src/courses/models.py
src/courses/signals.py
src/courses/tests/test_models.py

Delete cover images

---

src/settings/settings.py

Added default for auto fields
